### PR TITLE
chore: Remove unused variable

### PR DESCRIPTION
**Pull request by markbeierl**
# Description

Explicitly set the track to use for each module.

# Checklist:

- [X] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation https://github.com/canonical/charmed-5g/pull/201
N/A I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules https://github.com/canonical/sdcore-nms-k8s-operator/pull/104
N/A I have bumped the version of the library

### CODE REVIEW

**Review by ghislainbourgeois — APPROVED** [review]
Approved, but before merging, I suggest you change the title of the PR as it does not seem to match and the commit message will be that title.

**Comment by markbeierl** [comment]
Turns out these are not needed. @Gmerold, should I be deleting all these files, or are some stiff used?

**Comment by Gmerold** [comment]
> Turns out these are not needed. @Gmerold, should I be deleting all these files, or are some stiff used?

Not sure what do you mean by `all these files`, as I only see the removal of one variable. And that one is unused indeed and should be removed.

**Review by Gmerold — APPROVED** [review]

**Comment by markbeierl** [comment]
> Not sure what do you mean by `all these files`, as I only see the removal of one variable. And that one is unused indeed and should be removed.

I meant to ask if any of the files in this directory were being used or are they all deprecated now?

**Comment by Gmerold** [comment]
> > Not sure what do you mean by `all these files`, as I only see the removal of one variable. And that one is unused indeed and should be removed.
> 
> I meant to ask if any of the files in this directory were being used or are they all deprecated now?

Oh, ok. Yes, these files are very much being used. The official SD-Core root module doesn't contain the router and the gnbsim, both of which are needed for the tests. This module here combines all the required pieces.

**Pull request merged**
